
// --- File: AiSummaryDialog.tsx ---
// Description: Dialog component to display an AI-generated product summary.
"use client";

import React from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogClose } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Loader2, Bot } from "lucide-react";
import type { DigitalProductPassport } from '@/types/dpp';

interface AiSummaryDialogProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  summary: string | null;
  isLoading: boolean;
  product: DigitalProductPassport | null;
}

export function AiSummaryDialog({ isOpen, onOpenChange, summary, isLoading, product }: AiSummaryDialogProps) {
  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center">
            <Bot className="mr-2 h-5 w-5 text-primary" />
            AI Summary for: {product?.productName || "Product"}
          </DialogTitle>
          <DialogDescription>
            This summary is generated by AI and may require verification.
          </DialogDescription>
        </DialogHeader>
        <div className="py-4 min-h-[150px]">
          {isLoading ? (
            <div className="flex items-center justify-center h-full">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
              <p className="ml-2 text-muted-foreground">Generating summary...</p>
            </div>
          ) : summary ? (
            <p className="text-sm whitespace-pre-line">{summary}</p>
          ) : (
            <p className="text-sm text-muted-foreground">Could not generate summary at this time.</p>
          )}
        </div>
        <DialogClose asChild>
          <Button type="button" variant="outline">
            Close
          </Button>
        </DialogClose>
      </DialogContent>
    </Dialog>
  );
}
